export const LOGIN_ACTIONS = {
  G_SIGNIN_SUCCESS: 'G_SIGNIN_SUCCESS',
  G_SIGNIN_FAILURE: 'G_SIGNIN_FAILURE'
};

export const LIVE_ACTIONS = {
  SNAPSHOT: 'SNAPSHOT'
};

export const GAME_ACTIONS = {
  SET_LEVEL: 'SET_LEVEL',
  SET_STATUS: 'SET_STATUS'
};
